
export const MODUS_OPERANDI_CATEGORIES = [
  "FURTO IN ABITAZIONE",
  "FURTO DI AUTOVETTURA",
  "FURTO SU AUTOVETTURA",
  "FURTO CON STRAPPO",
  "FURTO CON DESTREZZA",
  "RAPINA IN PUBBLICA VIA",
  "RAPINA IN ESERCIZIO COMMERCIALE",
  "TRUFFA AGGLI ANZIANI",
  "TRUFFA ON-LINE",
  "ESTORSIONE",
  "USURA",
  "DETENZIONE AI FINI DI SPACCIO DI STUPEFACENTI",
  "TRAFFICO DI STUPEFACENTI",
  "GUIDA SOTTO L'INFLUENZA DELL'ALCOOL",
  "GUIDA SOTTO L'EFFETTO DI STUPEFACENTI",
  "RESISTENZA A PUBBLICO UFFICIALE",
  "OLTRAGGIO A PUBBLICO UFFICIALE",
  "LESIONI PERSONALI",
  "PERCOSSE",
  "MINACCIA",
  "STALKING / ATTI PERSECUTORI",
  "MALTRATTAMENTI IN FAMIGLIA",
  "VIOLENZA SESSUALE",
  "RICETTAZIONE",
  "RICICLAGGIO",
  "DANNEGGIAMENTO",
  "INCENDIO DOLOSO",
  "PORTO ABUSIVO DI ARMI",
  "EVASIONE",
  "FAVOREGGIAMENTO",
  "ALTRO REATO CONTRO IL PATRIMONIO",
  "ALTRO REATO CONTRO LA PERSONA",
  "ALTRO REATO CONTRO LA PUBBLICA AMMINISTRAZIONE",
  "ALTRO REATO IN MATERIA DI STUPEFACENTI"
];

/**
 * Normalizes a modus operandi string to one of the standard categories.
 * Uses simple keyword matching.
 */
export function normalizeModusOperandi(input: string): string {
  if (!input) return "ALTRO REATO";
  const upper = input.toUpperCase().trim();
  
  // Check for exact match first
  if (MODUS_OPERANDI_CATEGORIES.includes(upper)) return upper;

  // Keyword mapping
  const mapping: Record<string, string[]> = {
    "FURTO IN ABITAZIONE": ["ABITAZIONE", "CASA", "APPARTAMENTO", "DOMICILIO", "VILLA", "ALLOGGIO"],
    "FURTO DI AUTOVETTURA": ["FURTO AUTO", "FURTO MACCHINA", "FURTO VEICOLO", "RUBATA AUTO", "AUTOVETTURA"],
    "FURTO SU AUTOVETTURA": ["SU AUTO", "INTERNO AUTO", "ROTTURA CRISTALLO", "DEFLETTORE", "CATALIZZATORE", "RUOTA DI SCORTA"],
    "FURTO CON STRAPPO": ["STRAPPO", "SCIPPO", "SCIPPATA"],
    "FURTO CON DESTREZZA": ["DESTREZZA", "BORSEGGIATORE", "BORSEGGIO", "ABILE MANOVRA"],
    "RAPINA IN PUBBLICA VIA": ["RAPINA STRADA", "RAPINA VIA", "SOTTO MINACCIA DI ARMA", "PISTOLA ALLA TEMPIA", "RAPINA"],
    "TRUFFA AGGLI ANZIANI": ["ANZIANI", "NONNI", "MINORATA DIFESA", "FALSO CARABINIERE", "FALSO AVVOCATO"],
    "TRUFFA ON-LINE": ["ONLINE", "INTERNET", "SITO", "WEB", "E-COMMERCE", "FACEBOOK", "SUBITO.IT", "WHATSAPP"],
    "DETENZIONE AI FINI DI SPACCIO DI STUPEFACENTI": ["SPACCIO", "STUPEFACENTI", "DROGA", "HASHISH", "COCAINA", "MARIJUANA", "DETENZIONE AI FINI"],
    "GUIDA SOTTO L'INFLUENZA DELL'ALCOOL": ["EBBREZZA", "ALCOOL", "ALCOL", "ETILOMETRO", "UBRIACO"],
    "GUIDA SOTTO L'EFFETTO DI STUPEFACENTI": ["EFFETTO STUPEFACENTI", "DROGATO", "ALTERAZIONE PSICOFISICA", "ASSUNZIONE DROGA"],
    "LESIONI PERSONALI": ["LESIONI", "FERIMENTO", "AGGRESSIONE", "BOTTE", "PUGNO", "SCHIAFFO"],
    "STALKING / ATTI PERSECUTORI": ["STALKING", "PERSECUTORI", "AMMONIMENTO", "MOLESTIE"],
    "MALTRATTAMENTI IN FAMIGLIA": ["MALTRATTAMENTI", "FAMIGLIA", "MOGLIE", "FIGLI", "DOMESTICA", "CONVIVENTE"],
    "PORTO ABUSIVO DI ARMI": ["ARMI", "COLTELLO", "PISTOLA", "OGGETTO ATTO AD OFFENDERE", "PUGNALE"],
    "RESISTENZA A PUBBLICO UFFICIALE": ["RESISTENZA", "FUGA", "POSTO DI BLOCCO", "SPINTONAMENTO"],
    "DANNEGGIAMENTO": ["DANNEGGIAMENTO", "ATTO VANDALICO", "VANDALISMO", "IMBRATTAMENTO"],
    "RICETTAZIONE": ["RICETTAZIONE", "PROVENIENZA FURTO"],
    "USURA": ["USURA", "STROZZINAGGIO", "INTERESSI"],
    "ESTORSIONE": ["ESTORSIONE", "RICATTO", "MAZZETTA", "PIZZO"]
  };

  for (const [category, keywords] of Object.entries(mapping)) {
    if (keywords.some(kw => upper.includes(kw))) {
      return category;
    }
  }

  return upper; // Fallback to uppercase input if no keyword matches
}
